targets:
  $default:
    builders:
      drift_dev:
        options:
          test_dir: test/drift/
          schema_dir: drift_schemas/
          databases:
            prod: lib/shared_kernel/infrastructure/database/database.dart
          store_date_time_values_as_text: true
          sql:
            dialects:
              - postgres