name: dle_server
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  dotenv: ^4.2.0
  drift: ^2.26.0
  drift_postgres: ^1.3.0
  get_it: ^8.0.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  uuid: ^4.5.1
  postgres: ^3.5.4
  json_annotation: ^4.9.0
  dart_mappable: ^4.3.1
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.1.1
  collection: ^1.19.1
  logger: ^2.5.0
  injectable: ^2.5.0
  ruta: ^0.1.11
  dartz: ^0.10.1

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  drift_dev: ^2.26.0
  dart_mappable_builder: ^4.3.1+1
  injectable_generator: ^2.6.2
  ruta_generator: ^0.1.8

